---

disk_password: "guestdisk"

data_volumes:
  - name: data
    type: disk
    disks:
      - "vdb"
    fs_type: xfs
    mount_point: /mnt/guest
    encryption: true
    encryption_password: "{{ disk_password }}"

luks_bindings:
  - device: /dev/mapper/rhel-root
    encryption_password: "diskpassword"
    servers: "{{ tang_urls }}"
    state: present
    threshold: 1
    password_temporary: false

  - device: /dev/mapper/rhel-swap
    encryption_password: "diskpassword"
    servers: "{{ tang_urls }}"
    state: present
    threshold: 1
    password_temporary: false

  - device: /dev/vdb
    encryption_password: "{{ disk_password }}"
    servers: "{{ tang_urls }}"
    state: present
    threshold: 1
    password_temporary: false
